name: Build and Deploy to Ubuntu EC2

on:
  push:
    branches: [ main ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout source
        uses: actions/checkout@v4

      # 2️⃣ Setup JDK 17
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3️⃣ Build Spring Boot JAR
      - name: Build with Maven
        run: ./mvnw clean package -DskipTests

      # 4️⃣ Copy JAR to EC2 using SCP
      - name: Copy JAR to EC2
        uses: appleboy/scp-action@v0.1.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "target/*.jar"
          target: "/home/ubuntu/springbootapp/"

      # 5️⃣ SSH into EC2 and restart app
      - name: Restart app on EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/springbootapp
            pkill -f 'java -jar' || true
            nohup java -jar target/*.jar > app.log 2>&1 &
            echo "✅ App restarted successfully on EC2"
