name: Deploy Spring boot Application

on:
  push:
    branches:
      - develop
      - main

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '25'
      - name: Maven Build
        run: mvn clean install -DskipTests
  test:
    needs: init
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '25'
      - name: run test cases
        run: mvn clean test
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Configuration AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: AKIAZ25BUUJV56I3M5OM
          aws-secret-access-key: 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
          aws-region: "eu-north-1"
      - name: login in ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - name: Build Docker Image
        run: docker build -t testing/spring-app .
      - name: Tag Docker Image
        run: docker tag testing/spring-app:latest ${{ steps.login-ecr.outputs.registry }}/testing/spring-app:latest
      - name: Push Docker Image to ECR
        run: docker push ${{ steps.login-ecr.outputs.registry }}/testing/spring-app:latest
